### ISSUE TITLE
可拖动涂鸦

### ISSUE THREAD

**Issue by Firewayer** [1993hzw/Graffiti#1]
hi，想请问下博主，在现有项目的基础上想增强涂鸦可拖动，删除功能（类似图层拖动删除）难度大吗？  博主的实现思路大概是怎样的，有哪些难点呢。  谢谢啦，想了好一会，感觉还是不太会造轮子

**Comment by 1993hzw** [comment]
给每一次的涂鸦操作（GraffitiPath）记录它的矩形范围，每次点击判断点中了哪个涂鸦的矩形范围，然后移动该矩形范围；涂鸦时应根据在矩形范围内涂鸦．

**Comment by Firewayer** [comment]
嗯嗯，博主，功能已实现，通过在空白Bitmap中画GraffitiPath，然后截取Bitmap，加载进ImageView，再添加到一个通用容器中， 就实现了拖拽涂鸦。

**Comment by 1993hzw** [comment]
我加入了文字功能，文字支持拖动缩放。可以参考这个思路实现涂鸦拖动。
