### ISSUE TITLE
跳转很懵逼

### ISSUE THREAD

**Issue by Chenshuai770** [1993hzw/Graffiti#10]
大神,你好,我这边是直接从网下下载的图片,不是从本地库涂鸦,然后我一直跳转不到GraffitiActivity里面去,
Intent intent = new Intent(this, GraffitiActivity.class);
                GraffitiParams params=new GraffitiParams();
                intent.putExtra(GraffitiActivity.KEY_PARAMS,  params );
                startActivity(intent);
这样跳过不去

**Comment by 1993hzw** [comment]
这个你没有传图片路径。params.mImagePath =  filePath。你可以先把图片下载到sd，然后把sd上的图片路径传进来。

**Comment by Chenshuai770** [comment]
谢谢呢,不过我还有个问题,怎么能拿到涂鸦后的点的List的集合
