### ISSUE TITLE
我想知道如何保存涂鸦下的点

### ISSUE THREAD

**Issue by Chenshuai770** [1993hzw/Graffiti#11]
作者,您好,非常感谢您写了这个框架并开源,但实在有些复杂,作为新手的我不是很看的明白,目前我遇到的问题是比如我在图片上画一条直线,我需要保存这条直线上的所有的点,如果再画一条直线,我需要再保存一下这条直线上的点.还有就是如果撤销的话我得取消保存点,请问这些如何操作(如果实现困难可以不考虑撤销操作);非常感谢

**Comment by 1993hzw** [comment]
两个点确定一条直线。你要保存直线上的所有点？还是确定直线的这两个点？

**Comment by Chenshuai770** [comment]
直线上所有的点的集合,不用保存直线上的点

**Comment by Chenshuai770** [comment]
我看了源码,好像是在   mCurrPath.quadTo(
                                    toX(mLastTouchX),
                                    toY(mLastTouchY),
                                    toX((mTouchX + mLastTouchX) / 2),
                                    toY((mTouchY + mLastTouchY) / 2));这里有所有的点得集合,但这里有两个地方调用了,一个是Move得时候,另外一个是Cancel上也有,这里不是很清楚要怎么去保存

**Comment by Chenshuai770** [comment]
我想知道怎么保存涂鸦上的点的坐标,相对于图片而言,而不是手机屏幕

**Comment by 1993hzw** [comment]
toX() toY()就是把屏幕坐标转换成图片坐标。或者你可以在mPathStack这个集合里找到所有涂鸦的坐标信息。

**Comment by Chenshuai770** [comment]
楼主,你好.mPathStack的集合好像只记载了按下和抬起这两个点得集合,那么在move中怎么把一条线上的点给记录下来

**Comment by 1993hzw** [comment]
move记录在了GraffitPath里面的Path变量。
