### ISSUE TITLE
我想知道怎么拿到文字的集合

### ISSUE THREAD

**Issue by Chenshuai770** [1993hzw/Graffiti#12]
我想知道GraffitiView里面的到文字的左边和文字信息,就是默认不旋转不平移的情况下,能在Up事件里面得到吗还是哪里

**Comment by Chenshuai770** [comment]
我想知道在GraffitiView里面的触摸事件中,怎么把手绘和画文字的撤销操作绑定在一起,我重新new了两个list一个是记录手绘的,另外一个是记录text的点,但是撤销操作需要怎么样才能绑定在一起,谢谢

**Comment by 1993hzw** [comment]
GraffitiListener.onCreateSelectableItem(GraffitiView.Pen pen, float x, float y) 这个方法可以获取到文字的位置xy

**Comment by 1993hzw** [comment]
那个手绘和文字操作的撤销绑定在一起是什么意思呢
