### ISSUE TITLE
有毛边

### ISSUE THREAD

**Issue by tulongchao** [1993hzw/Graffiti#14]

**Comment by 1993hzw** [comment]
没弄明白。可以详细描述下吗

**Comment by tulongchao** [comment]
不好意思，没有描述清楚，有锯齿，除了画矩形外其余的都有锯齿

**Comment by 1993hzw** [comment]
这个跟你导入的图片尺寸有关。如果你的图片大小很小，比如90x90,那么肯定画在上面的图形是有锯齿的，因为图片的像素点少

**Comment by tulongchao** [comment]
我的图片是截屏的，        // 关闭硬件加速，因为bitmap的Canvas不支持硬件加速
//        if (Build.VERSION.SDK_INT >= 11) {
//            setLayerType(LAYER_TYPE_SOFTWARE, null);
//        }
我把这句代码注释掉就好了，奇怪。

**Comment by 1993hzw** [comment]
...注释这个后，你试试画矩形

**Comment by tulongchao** [comment]
注释后，画矩形没有问题，不注释掉，除了画矩形外，都有问题
