### ISSUE TITLE
大神能否加一个裁剪的功能啊

### ISSUE THREAD

**Issue by wenxushen** [1993hzw/Graffiti#5]

**Comment by 1993hzw** [comment]
你可以对一张图片裁剪后再涂鸦。如果是对一张正在涂鸦的图片进行裁剪的话，同时又要保留之前的涂鸦，并还要支持撤销这些操作，就有点麻烦了。

**Comment by wenxushen** [comment]
确实麻烦，最近公司要求做一个类似微信的图片编辑的功能，看了微信的功能后发现确实难搞
