### ISSUE TITLE
超大图片涂鸦有什么思路吗

### ISSUE THREAD

**Issue by gordonpro** [1993hzw/Graffiti#6]
现在如果涂鸦一张 8000 x 6000 的图片，大部分机器加载到Bitmap去显示时，已经挂了，涂鸦步骤都无法继续。

**Comment by 1993hzw** [comment]
https://stackoverflow.com/questions/31969996/how-do-i-edit-and-save-a-large-bitmap-in-android-currently-writing-it-out-as-ti
可以参考上面的回答。使用BitmapRegionDecoder解析图片，PNGJ保存图片。
