### ISSUE TITLE
跳转有点蒙

### ISSUE THREAD

**Issue by wl960127** [1993hzw/Graffiti#8]
请问一下：一开始是点击事件     ImageSelectorActivity.startActivityForResult(REQ_CODE_SELECT_IMAGE, getActivity(), null, false); 

然后 响应CODE 进行 操作么？requestCode == REQ_CODE_SELECT_IMAGE  之后的操作完全没有响应，只是跳转选择图片，确认就退出了（我是没有写案例的 MainActivity ，在一个fragment中点击跳转后，到选择图片，然后确认。就没有进去，直接关闭了。我需要获取到修改后的图片路径）

**Comment by 1993hzw** [comment]
你确定选择图片后，你的fragment能收到系统的onActivityResult()的回调吗？

**Comment by wl960127** [comment]
好像是接不到回调 选择图片确认就直接 退了 ，因为frgamen有onActivityResult 的处理 ，我就直接把响应码的逻辑写在里面了。

**Comment by wl960127** [comment]
网上看的很多 方法都行不通 走不到请求码这里面

**Comment by 1993hzw** [comment]
推荐一篇文章给你。http://www.cnblogs.com/tangZH/archive/2016/10/04/5930491.html。尝试下里面的方法
